name: natpass-builder

on:
  push:
    branches: [ builder ]
  schedule:
    - cron: '30 0 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: builder